# Generated by Django 5.1.15 on 2026-06-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0278_alter_findingexclusion_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='risk_status',
            field=models.CharField(
                choices=[
                    ('Risk Pending', 'Risk Pending'),
                    ('Risk Rejected', 'Risk Rejected'),
                    ('Risk Expired', 'Risk Expired'),
                    ('Risk Accepted', 'Risk Accepted'),
                    ('Risk Reviewed', 'Risk Reviewed'),
                    ('Risk Active', 'Risk Active'),
                    ('On Whitelist', 'On Whitelist'),
                    ('On Blacklist', 'On Blacklist'),
                    ('On ZeroDay', 'On ZeroDay'),
                    ('Transfer Pending', 'Transfer Pending'),
                    ('Transfer Rejected', 'Transfer Rejected'),
                    ('Transfer Expired', 'Transfer Expired'),
                    ('Transfer Accepted', 'Transfer Accepted'),
                ],
                default='Risk Active',
                help_text='Denotes the type of finding status, (pending, rejected).',
                max_length=20,
                null=True,
                verbose_name='Risk Status',
            ),
        ),
    ]
